version: '3.5'

services:
  symfony_vue_web:
    container_name: symfony_vue_web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "201:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony_vue_be
    networks:
      - symfony_vue_network

  symfony_vue_be:
    container_name: symfony_vue_be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9010
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony_vue_db
    networks:
      - symfony_vue_network
        

  symfony_vue_db:
    container_name: symfony_vue_db
    image: mysql:8.0
    ports:
      - "36000:3306"
    environment:
      MYSQL_DATABASE: symfony_vue_db
      MYSQL_USER: symfony_vue_db
      MYSQL_PASSWORD: symfony_vue_db
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony_vue_data:/var/lib/mysql
    networks:
      - symfony_vue_network


volumes:
  symfony_vue_data:

networks:
  symfony_vue_network:
    external: true
